on:
  schedule:
    - cron:  '0 7 * * 2,5'
    # scheduled at 07:00 every Tuesday and Friday
  workflow_dispatch:

jobs:
  sync_with_upstream:
    runs-on: ubuntu-latest
    name: Sync mainwith upstream latest

    steps:
    - name: Checkout main
      uses: actions/checkout@v2
      with:
        ref: main
        
    - name: Pull upstream changes
      id: sync
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        target_sync_branch: main
        # REQUIRED 'target_repo_token' exactly like this!
        target_repo_token: ${{ secrets.MY_WORKFLOW_TOKEN}}
        upstream_sync_branch: main
        upstream_sync_repo: NEFSC/READ-SSB-Lee-WorkingEfficiently
        # Set test_mode true to run tests instead of the true action!!
        test_mode: false

    - name: Timestamp
      run: date
